
CREATE PROCEDURE OBPROD.CALCULATEDISCOUNTEDBIDCOST  ( IN I_RFPID INTEGER )  
    

BEGIN

DECLARE L_BATCHID INTEGER;
DECLARE L_SHIPPERID INTEGER;
DECLARE L_ROUNDNUM INTEGER;
DECLARE i INTEGER;

SELECT MAX(BATCHID) INTO L_BATCHID FROM LTL_SHIPMENT_BATCH WHERE RFPID = I_RFPID;
SELECT MAX(ROUND_NUM) INTO L_ROUNDNUM  FROM RFP  WHERE RFPID = I_RFPID;
SELECT DISTINCT TCCOMPANYID  INTO L_SHIPPERID  FROM RFP  WHERE RFPID = I_RFPID;

IF L_BATCHID IS NOT NULL THEN

	SET i = 0;

	FOR lbs AS
	
	    SELECT rfpid, laneid,  LANEEQUIPMENTTYPEID,   OBCARRIERCODEID,  PACKAGEID, max(round_num) roundnum
	    FROM   LANEBID
	    WHERE  RFPID=i_rfpid
	    GROUP BY rfpid, laneid,  LANEEQUIPMENTTYPEID,  OBCARRIERCODEID,  PACKAGEID 
	DO 
	UPDATE LANEBID SET DISCOUNTBIDCOST =
	    ( SELECT  TRUNC(CAST(SUM(GREATEST(COALESCE(LANEBID.MINIMUMCHARGE,0), COALESCE(s.SHIPMENTRATE, 0) * COALESCE(s.SOURCINGFACTOR, 1) * (1 - (
	COALESCE(LANEBID.RATEDISCOUNT,0)/100)))) AS DECIMAL (24,3)) / COALESCE(SUM(s.SOURCINGFACTOR), COUNT(*)), 3)
	      FROM LTL_SHIPMENT s
	      WHERE s.BATCHID = L_BATCHID AND
		    s.SHIPPERID = L_SHIPPERID AND
		    LANEBID.LANEID = lbs.LANEID AND
		    LANEBID.LANEID = s.LANEID
	    )
	  WHERE RFPID = lbs.RFPID AND
		ROUND_NUM = lbs.ROUNDNUM AND
		LANEID = lbs.LANEID  AND
		LANEEQUIPMENTTYPEID = lbs.LANEEQUIPMENTTYPEID AND
		OBCARRIERCODEID = lbs.OBCARRIERCODEID AND
		PACKAGEID = lbs.PACKAGEID;
	    SET i = i + 1;
	    if ( i >= 1000)  THEN
	      --commit;
	      SET i = 0;
	    END if;
	END FOR;

ELSE
	FOR lbs  AS
		SELECT  rfpid,  laneid,  LANEEQUIPMENTTYPEID,  OBCARRIERCODEID,  PACKAGEID,  max(round_num) ROUNDNUM
		     FROM    LANEBID
		     WHERE   RFPID=I_RFPID
		     GROUP BY RFPID, LANEID,  LANEEQUIPMENTTYPEID,  OBCARRIERCODEID,  PACKAGEID
	DO
	UPDATE  LANEBID  SET DISCOUNTBIDCOST =
	    ( SELECT  TRUNC( COALESCE(l.SHIPMENTRATEDCOST, 0) * (1 - (CAST ( COALESCE(LANEBID.RATEDISCOUNT, 0) AS DECIMAL(24,3)) / 100)), 3)
	      FROM LANE l
	      WHERE l.RFPID = I_RFPID AND l.LANEID = LANEBID.LANEID
	    )
	WHERE RFPID = lbs.RFPID AND
	      LANEID = lbs.LANEID AND
	      LANEEQUIPMENTTYPEID = lbs.LANEEQUIPMENTTYPEID AND
	      OBCARRIERCODEID = lbs.OBCARRIERCODEID AND
	      PACKAGEID = lbs.PACKAGEID AND
	      ROUND_NUM = lbs.ROUNDNUM;
	END FOR;
END IF;
	
	
FOR lbs AS
   SELECT  rfpid,  laneid, LANEEQUIPMENTTYPEID,  OBCARRIERCODEID,  PACKAGEID,  max(round_num) ROUNDNUM
	     FROM    LANEBID
	     WHERE   RFPID=I_RFPID
	     GROUP BY RFPID, LANEID,  LANEEQUIPMENTTYPEID,  OBCARRIERCODEID,  PACKAGEID 
DO
UPDATE LANEBID  SET COSTPERLOAD = GREATEST ( COALESCE(DISCOUNTBIDCOST, 0), COALESCE(COSTPERLOAD, 0) )
    WHERE RFPID = lbs.RFPID AND
	  LANEID = lbs.LANEID AND
	  LANEEQUIPMENTTYPEID = lbs.LANEEQUIPMENTTYPEID AND
	  OBCARRIERCODEID = lbs.OBCARRIERCODEID AND
	  PACKAGEID = lbs.PACKAGEID AND
	  ROUND_NUM = lbs.ROUNDNUM;
END FOR;

END
GO
